require 'digest'
require 'fileutils'

module Jekyll
  module AssetHash
    def asset_hash(input)
      site = @context.registers[:site]
      
      # Handle JS files (they exist in source)
      if input.include?('.js')
        asset_path = File.join(site.source, input.gsub(/^\//, ''))
        
        if File.exist?(asset_path)
          content = File.read(asset_path)
          hash = Digest::SHA256.hexdigest(content)[0..7]
          
          ext = File.extname(input)
          base = File.basename(input, ext)
          dir = File.dirname(input)
          
          hashed_name = "#{base}-#{hash}#{ext}"
          hashed_path = dir == '.' ? hashed_name : "#{dir}/#{hashed_name}"
          result = "/#{hashed_path.gsub(/^\//, '')}"  # Remove double slashes
          
          return result
        else
          return input
        end
      end
      
      # Handle CSS files (will be generated by Jekyll)
      if input.include?('.css')
        # Use site time + CSS source content to generate consistent hash
        css_source = File.join(site.source, 'css/main.scss')
        
        if File.exist?(css_source)
          source_content = File.read(css_source)
          # Include site time to ensure uniqueness per build
          hash_content = source_content + site.time.to_s
          hash = Digest::SHA256.hexdigest(hash_content)[0..7]
          
          result = "/css/main-#{hash}.css"
          return result
        else
          return input
        end
      end
      
      return input
    end
  end
end

Liquid::Template.register_filter(Jekyll::AssetHash)

# Hook to create hashed asset files
Jekyll::Hooks.register :site, :post_write do |site|
  Dir.glob(File.join(site.dest, '**/*.html')).each do |html_file|
    content = File.read(html_file)
    
    # Find CSS hash references
    css_matches = content.scan(/\/css\/main-([a-f0-9]{8})\.css/)
    css_matches.each do |match|
      hash = match[0]
      original_css = File.join(site.dest, 'css/main.css')
      hashed_css = File.join(site.dest, "css/main-#{hash}.css")
      
      if File.exist?(original_css) && !File.exist?(hashed_css)
        FileUtils.cp(original_css, hashed_css)
      end
    end
    
    # Find JS hash references
    js_matches = content.scan(/\/js\/(jquery\.min|[-\w]+)-([a-f0-9]{8})\.js/)
    js_matches.each do |match|
      js_name = match[0]
      hash = match[1]
      original_js = File.join(site.source, "js/#{js_name}.js")
      hashed_js = File.join(site.dest, "js/#{js_name}-#{hash}.js")
      
      if File.exist?(original_js) && !File.exist?(hashed_js)
        FileUtils.cp(original_js, hashed_js)
      end
    end
  end
end